version: 0.1
log:
  level: debug
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  cache:
    blobdescriptor: inmemory
  maintenance:
    readonly:
      enabled: true
http:
  addr: :5000
  secret: asecretforlocaldevelopment
  debug:
    addr: :5001
  tls:
    certificate: /certs/fullchain.pem
    key: /certs/privkey.pem