---
apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
  labels:
    component: etcd
    tier: control-plane
spec:
  hostNetwork: true
  containers:
  - image: uk8s.com/coreos/etcd:v3.0.15
    name: etcd
    command:
    - etcd
    - --listen-client-urls
    - http://127.0.0.1:2379
    - --advertise-client-urls
    - http://127.0.0.1:2379
    - --data-dir
    - /var/etcd/data
    volumeMounts:
    - name: certs
      mountPath: /etc/ssl/certs
    - name: etcd
      mountPath: /var/etcd
    - name: k8s
      readOnly: true
      mountPath: /etc/kubernetes/
    livenessProbe:
      httpGet:
        path: "/health"
        port: 2379
        host: 127.0.0.1
      initialDelaySeconds: 15
      timeoutSeconds: 15
      failureThreshold: 8
    securityContext:
      seLinuxOptions:
        type: spc_t
  volumes:
  - name: certs
    hostPath:
      path: /etc/ssl/certs
  - name: etcd
    hostPath:
      path: /var/lib/etcd
  - name: k8s
    hostPath:
      path: /etc/kubernetes